<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>E:\TzAppData\AGCV2\AutoGCLib\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>E:\TzAppData\AGCV2\AutoGCLib\bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Templates\TypeScript\Ai2Columns.sbn" />
    <None Remove="Templates\TypeScript\Ai3Query.sbn" />
    <None Remove="Templates\TypeScript\Ai4Base.sbn" />
    <None Remove="Templates\TypeScript\Ai4Command.sbn" />
    <None Remove="Templates\TypeScript\EditAi.sbn" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="GeneCodeV8\JavaScript\" />
    <Folder Include="PrjFunction\" />
    <Folder Include="Properties\" />
    <Folder Include="Templates\Vue_ViewScript_Edit_TS4Html\" />
  </ItemGroup>
	<ItemGroup>
		<Reference Include="System.Web" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgcBase\AgcBase.csproj" />
    <ProjectReference Include="..\AgcBLLEx\AgcBLLEx.csproj" />
    <ProjectReference Include="..\AgcCommBase\AgcCommBase.csproj" />
    <ProjectReference Include="..\AgcDAL\AgcDAL.csproj" />
    <ProjectReference Include="..\AgcEntity\AgcEntity.csproj" />
    <ProjectReference Include="..\AgcPureClassBL\AgcPureClassBL.csproj" />
    <ProjectReference Include="..\AgcPureClass\AgcPureClass.csproj" />
    <ProjectReference Include="..\CodeStruct\CodeStruct.csproj" />
    <ProjectReference Include="..\TzAdvancedLib\TzAdvancedLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Templates\TypeScript\Ai2Columns.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\TypeScript\Ai4Base.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\TypeScript\Ai4Command.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\TypeScript\EditAi.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\Vue_ViewScript_TS4Html\Gen_CRUD_setup_btnUpdate_Click.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Scriban" Version="7.0.6" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Templates\TypeScript\Ai3Query.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PubDataBase">
      <HintPath>..\..\..\PrjCode\PublicLib\PubDataBase.dll</HintPath>
    </Reference>
    <Reference Include="TzCommWebServerCtrlLib">
      <HintPath>..\..\..\PrjCode\PublicLib\TzCommWebServerCtrlLib.dll</HintPath>
    </Reference>
    <Reference Include="TzPubFunction">
      <HintPath>..\..\..\PrjCode\PublicLib\TzPubFunction.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>